import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { api } from "../api.js";

export default function Home() {
  const [health, setHealth] = useState(null);
  const [healthError, setHealthError] = useState(null);

  useEffect(() => {
    api
      .getHealth()
      .then(setHealth)
      .catch((err) => setHealthError(err.message || "Could not reach the local backend on http://localhost:8000."));
  }, []);

  return (
    <div>
      <div className="card">
        <h1 style={{ marginTop: 0 }}>English & TOEFL Speaking Coach</h1>
        <p className="muted">
          Practice free-form English conversation or full TOEFL iBT Speaking tasks. Recordings are transcribed
          locally with faster-whisper, and feedback is generated by FreeLLMAPI running on your machine.
        </p>
      </div>

      {healthError && (
        <div className="error-box">
          Could not reach the local backend at http://localhost:8000. Make sure it's running (see README):{"\n"}
          {healthError}
        </div>
      )}

      {health && (
        <div className="card">
          <p className="section-title">System status</p>
          <div className="grid cols-2">
            <div>
              <div className="flex-between">
                <span>FreeLLMAPI</span>
                <span className={`badge ${health.llm.reachable ? "good" : "bad"}`}>
                  {health.llm.reachable ? "Connected" : "Unreachable"}
                </span>
              </div>
              <p className="muted small">{health.llm.message}</p>
            </div>
            <div>
              <div className="flex-between">
                <span>faster-whisper</span>
                <span className={`badge ${health.whisper.installed ? "good" : "bad"}`}>
                  {health.whisper.installed ? "Installed" : "Missing"}
                </span>
              </div>
              <p className="muted small">{health.whisper.message}</p>
            </div>
          </div>
        </div>
      )}

      <div className="grid cols-2">
        <Link to="/general" style={{ textDecoration: "none" }}>
          <div className="card">
            <p className="section-title">🗨️ General English Practice</p>
            <p className="muted">
              Free conversation practice. Pick from 24+ everyday topics, record an answer of any length, and get
              friendly feedback on grammar, vocabulary, and clarity.
            </p>
          </div>
        </Link>
        <Link to="/toefl" style={{ textDecoration: "none" }}>
          <div className="card">
            <p className="section-title">🎓 TOEFL Speaking Practice</p>
            <p className="muted">
              Simulated TOEFL iBT Speaking Tasks 1-4 with official timing, reading passages, listening
              conversations/lectures, and rubric-based scoring.
            </p>
          </div>
        </Link>
      </div>
    </div>
  );
}
